/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *///
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.17 at 01:59:50 下午 CST 
//


package com.wisii.server;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SocketPoolSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="RunPoolSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="XSLTPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServerPort" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PdfPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Concurrency" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="RunPoolState">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="fixed"/>
 *               &lt;enumeration value="cached"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "socketPoolSize",
    "runPoolSize",
    "xsltPath",
    "serverPort",
    "pdfPath",
    "concurrency",
    "runPoolState"
})
@XmlRootElement(name = "ServerConfig")
public class ServerConfig {

    @XmlElement(name = "SocketPoolSize")
    protected int socketPoolSize;
    @XmlElement(name = "RunPoolSize")
    protected int runPoolSize;
    @XmlElement(name = "XSLTPath", required = true)
    protected String xsltPath;
    @XmlElement(name = "ServerPort")
    protected int serverPort;
    @XmlElement(name = "PdfPath", required = true)
    protected String pdfPath;
    @XmlElement(name = "Concurrency")
    protected boolean concurrency;
    @XmlElement(name = "RunPoolState", required = true)
    protected String runPoolState;

    /**
     * Gets the value of the socketPoolSize property.
     * 
     */
    public int getSocketPoolSize() {
        return socketPoolSize;
    }

    /**
     * Sets the value of the socketPoolSize property.
     * 
     */
    public void setSocketPoolSize(int value) {
        this.socketPoolSize = value;
    }

    /**
     * Gets the value of the runPoolSize property.
     * 
     */
    public int getRunPoolSize() {
        return runPoolSize;
    }

    /**
     * Sets the value of the runPoolSize property.
     * 
     */
    public void setRunPoolSize(int value) {
        this.runPoolSize = value;
    }

    /**
     * Gets the value of the xsltPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXSLTPath() {
        return xsltPath;
    }

    /**
     * Sets the value of the xsltPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXSLTPath(String value) {
        this.xsltPath = value;
    }

    /**
     * Gets the value of the serverPort property.
     * 
     */
    public int getServerPort() {
        return serverPort;
    }

    /**
     * Sets the value of the serverPort property.
     * 
     */
    public void setServerPort(int value) {
        this.serverPort = value;
    }

    /**
     * Gets the value of the pdfPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdfPath() {
        return pdfPath;
    }

    /**
     * Sets the value of the pdfPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdfPath(String value) {
        this.pdfPath = value;
    }

    /**
     * Gets the value of the concurrency property.
     * 
     */
    public boolean isConcurrency() {
        return concurrency;
    }

    /**
     * Sets the value of the concurrency property.
     * 
     */
    public void setConcurrency(boolean value) {
        this.concurrency = value;
    }

    /**
     * Gets the value of the runPoolState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunPoolState() {
        return runPoolState;
    }

    /**
     * Sets the value of the runPoolState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunPoolState(String value) {
        this.runPoolState = value;
    }

}
