/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *///
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.29 at 02:12:35 下午 CST 
//


package com.wisii.edit.tag.components.action.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wisii.edit.tag.components.action.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wisii.edit.tag.components.action.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TagSystemKeys }
     * 
     */
    public TagSystemKeys createTagSystemKeys() {
        return new TagSystemKeys();
    }

    /**
     * Create an instance of {@link TagSystemKeys.Date }
     * 
     */
    public TagSystemKeys.Date createTagSystemKeysDate() {
        return new TagSystemKeys.Date();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link TagSystemKeys.Select }
     * 
     */
    public TagSystemKeys.Select createTagSystemKeysSelect() {
        return new TagSystemKeys.Select();
    }
   
    /**
     * Create an instance of {@link TagSystemKeys.SingleLineInput }
     * 
     */
    public TagSystemKeys.SingleLineInput createTagSystemKeysSingleLineInput() {
        return new TagSystemKeys.SingleLineInput();
    }

    /**
     * Create an instance of {@link TagSystemKeys.Float }
     * 
     */
    public TagSystemKeys.Float createTagSystemKeysFloat() {
        return new TagSystemKeys.Float();
    }

    /**
     * Create an instance of {@link TagSystemKeys.Mainframe }
     * 
     */
    public TagSystemKeys.MainFrame createTagSystemKeysMainframe() {
        return new TagSystemKeys.MainFrame();
    }
    
    /**
     * Create an instance of {@link TagSystemKeys.MultiLineInput }
     * 
     */
    public TagSystemKeys.MultiLineInput createTagSystemKeysMultiLineInput() {
        return new TagSystemKeys.MultiLineInput();
    }

    /**
     * Create an instance of {@link TagSystemKeys.Checkbox }
     * 
     */
    public TagSystemKeys.Checkbox createTagSystemKeysCheckbox() {
        return new TagSystemKeys.Checkbox();
    }

    /**
     * Create an instance of {@link TagSystemKeys.BaseUrl }
     * 
     */
    public TagSystemKeys.BaseUrl createTagSystemKeysBaseUrl() {
        return new TagSystemKeys.BaseUrl();
    }

    /**
     * Create an instance of {@link TagSystemKeys.All }
     * 
     */
    public TagSystemKeys.All createTagSystemKeysAll() {
        return new TagSystemKeys.All();
    }

}
