/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *///
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.29 at 02:12:35 下午 CST 
//

package com.wisii.edit.tag.components.action.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;BaseUrl&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;attribute name=&quot;name&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *                 &lt;attribute name=&quot;global&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot; /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;All&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
 *                   &lt;element ref=&quot;{}key&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute ref=&quot;{}base-url&quot;/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;singleLineInput&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
 *                   &lt;element ref=&quot;{}key&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute ref=&quot;{}base-url&quot;/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;multiLineInput&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
 *                   &lt;element ref=&quot;{}key&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute ref=&quot;{}base-url&quot;/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;select&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
 *                   &lt;element ref=&quot;{}key&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute ref=&quot;{}base-url&quot;/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;date&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
 *                   &lt;element ref=&quot;{}key&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute ref=&quot;{}base-url&quot;/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;checkbox&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
 *                   &lt;element ref=&quot;{}key&quot;/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute ref=&quot;{}base-url&quot;/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;float&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
 *                   &lt;element ref=&quot;{}key&quot;/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute ref=&quot;{}base-url&quot;/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "baseUrl", "all", "singleLineInput",
		"multiLineInput", "select", "date", "checkbox", "_float", "mainFrame" })
@XmlRootElement(name = "TagSystemKeys")
public class TagSystemKeys {

	@XmlElement(name = "BaseUrl")
	protected List<TagSystemKeys.BaseUrl> baseUrl;
	@XmlElement(name = "All")
	protected TagSystemKeys.All all;
	protected TagSystemKeys.SingleLineInput singleLineInput;
	protected TagSystemKeys.MultiLineInput multiLineInput;
	protected TagSystemKeys.Select select;
	protected TagSystemKeys.Date date;
	protected TagSystemKeys.Checkbox checkbox;
	@XmlElement(name = "float")
	protected TagSystemKeys.Float _float;
	@XmlElement(name = "mainframe")
	protected TagSystemKeys.MainFrame mainFrame;

	/**
	 * Gets the value of the baseUrl property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the baseUrl property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBaseUrl().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link TagSystemKeys.BaseUrl }
	 * 
	 * 
	 */
	public List<TagSystemKeys.BaseUrl> getBaseUrl() {
		if (baseUrl == null) {
			baseUrl = new ArrayList<TagSystemKeys.BaseUrl>();
		}
		return this.baseUrl;
	}

	/**
	 * Gets the value of the all property.
	 * 
	 * @return possible object is {@link TagSystemKeys.All }
	 * 
	 */
	public TagSystemKeys.All getAll() {
		return all;
	}

	/**
	 * Sets the value of the all property.
	 * 
	 * @param value
	 *            allowed object is {@link TagSystemKeys.All }
	 * 
	 */
	public void setAll(TagSystemKeys.All value) {
		this.all = value;
	}

	/**
	 * Gets the value of the singleLineInput property.
	 * 
	 * @return possible object is {@link TagSystemKeys.SingleLineInput }
	 * 
	 */
	public TagSystemKeys.SingleLineInput getSingleLineInput() {
		return singleLineInput;
	}

	/**
	 * Sets the value of the singleLineInput property.
	 * 
	 * @param value
	 *            allowed object is {@link TagSystemKeys.SingleLineInput }
	 * 
	 */
	public void setSingleLineInput(TagSystemKeys.SingleLineInput value) {
		this.singleLineInput = value;
	}

	/**
	 * Gets the value of the multiLineInput property.
	 * 
	 * @return possible object is {@link TagSystemKeys.MultiLineInput }
	 * 
	 */
	public TagSystemKeys.MultiLineInput getMultiLineInput() {
		return multiLineInput;
	}

	/**
	 * Sets the value of the multiLineInput property.
	 * 
	 * @param value
	 *            allowed object is {@link TagSystemKeys.MultiLineInput }
	 * 
	 */
	public void setMultiLineInput(TagSystemKeys.MultiLineInput value) {
		this.multiLineInput = value;
	}

	/**
	 * Gets the value of the select property.
	 * 
	 * @return possible object is {@link TagSystemKeys.Select }
	 * 
	 */
	public TagSystemKeys.Select getSelect() {
		return select;
	}

	/**
	 * Sets the value of the select property.
	 * 
	 * @param value
	 *            allowed object is {@link TagSystemKeys.Select }
	 * 
	 */
	public void setSelect(TagSystemKeys.Select value) {
		this.select = value;
	}

	/**
	 * Gets the value of the date property.
	 * 
	 * @return possible object is {@link TagSystemKeys.Date }
	 * 
	 */
	public TagSystemKeys.Date getDate() {
		return date;
	}

	/**
	 * Sets the value of the date property.
	 * 
	 * @param value
	 *            allowed object is {@link TagSystemKeys.Date }
	 * 
	 */
	public void setDate(TagSystemKeys.Date value) {
		this.date = value;
	}

	/**
	 * Gets the value of the checkbox property.
	 * 
	 * @return possible object is {@link TagSystemKeys.Checkbox }
	 * 
	 */
	public TagSystemKeys.Checkbox getCheckbox() {
		return checkbox;
	}


	/**
	 * Sets the value of the checkbox property.
	 * 
	 * @param value
	 *            allowed object is {@link TagSystemKeys.Checkbox }
	 * 
	 */
	public void setCheckbox(TagSystemKeys.Checkbox value) {
		this.checkbox = value;
	}
	
	/**
	 * Gets the value of the float property.
	 * 
	 * @return possible object is {@link TagSystemKeys.Float }
	 * 
	 */
	public TagSystemKeys.Float getFloat() {
		return _float;
	}

	/**
	 * Sets the value of the float property.
	 * 
	 * @param value
	 *            allowed object is {@link TagSystemKeys.Float }
	 * 
	 */
	public void setFloat(TagSystemKeys.Float value) {
		this._float = value;
	}
	/**
	 * Sets the value of the mainFrame property.
	 * 
	 * @param value
	 *            allowed object is {@link TagSystemKeys.MainFrame }
	 * 
	 */
	public void setMainFrame(TagSystemKeys.MainFrame value) {
		this.mainFrame = value;
	}

	/**
	 * Gets the value of the mainFrame property.
	 * 
	 * @return possible object is {@link TagSystemKeys.MainFrame }
	 * 
	 */
	public TagSystemKeys.MainFrame getMainFrame() {
		return mainFrame;
	}
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
	 *         &lt;element ref=&quot;{}key&quot; maxOccurs=&quot;unbounded&quot;/&gt;
	 *       &lt;/choice&gt;
	 *       &lt;attribute ref=&quot;{}base-url&quot;/&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "key" })
	public static class All {

		protected List<Key> key;
		@XmlAttribute(name = "base-url")
		protected String baseUrl;

		/**
		 * Gets the value of the key property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the key property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getKey().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Key }
		 * 
		 * 
		 */
		public List<Key> getKey() {
			if (key == null) {
				key = new ArrayList<Key>();
			}
			return this.key;
		}

		/**
		 * Gets the value of the baseUrl property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getBaseUrl() {
			return baseUrl;
		}

		/**
		 * Sets the value of the baseUrl property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setBaseUrl(String value) {
			this.baseUrl = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;attribute name=&quot;name&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
	 *       &lt;attribute name=&quot;global&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot; /&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class BaseUrl {
		@XmlValue
		protected String content;
		@XmlAttribute
		protected String name;
		@XmlAttribute
		protected boolean global;

		/**
		 * Gets the value of the content property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 *     
		 */
		public String getContent() {
			return content;
		}
		/**
		 * Sets the value of the content property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *     
		 */
		public void setContent(String content) {
			this.content = content;
		}
		
		/**
		 * Gets the value of the name property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setName(String value) {
			this.name = value;
		}

		/**
		 * Gets the value of the global property.
		 * 
		 * @return possible object is {@link Boolean }
		 * 
		 */
		public boolean isGlobal() {
			return global;
		}

		/**
		 * Sets the value of the global property.
		 * 
		 * @param value
		 *            allowed object is {@link Boolean }
		 * 
		 */
		public void setGlobal(boolean value) {
			this.global = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
	 *         &lt;element ref=&quot;{}key&quot;/&gt;
	 *       &lt;/choice&gt;
	 *       &lt;attribute ref=&quot;{}base-url&quot;/&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "key" })
	public static class Checkbox {

		protected List<Key> key;
		@XmlAttribute(name = "base-url")
		protected String baseUrl;

		/**
		 * Gets the value of the key property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the key property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getKey().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Key }
		 * 
		 * 
		 */
		public List<Key> getKey() {
			if (key == null) {
				key = new ArrayList<Key>();
			}
			return this.key;
		}

		/**
		 * Gets the value of the baseUrl property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getBaseUrl() {
			return baseUrl;
		}

		/**
		 * Sets the value of the baseUrl property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setBaseUrl(String value) {
			this.baseUrl = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
	 *         &lt;element ref=&quot;{}key&quot; maxOccurs=&quot;unbounded&quot;/&gt;
	 *       &lt;/choice&gt;
	 *       &lt;attribute ref=&quot;{}base-url&quot;/&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "key" })
	public static class Date {

		protected List<Key> key;
		@XmlAttribute(name = "base-url")
		protected String baseUrl;

		/**
		 * Gets the value of the key property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the key property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getKey().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Key }
		 * 
		 * 
		 */
		public List<Key> getKey() {
			if (key == null) {
				key = new ArrayList<Key>();
			}
			return this.key;
		}

		/**
		 * Gets the value of the baseUrl property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getBaseUrl() {
			return baseUrl;
		}

		/**
		 * Sets the value of the baseUrl property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setBaseUrl(String value) {
			this.baseUrl = value;
		}

	}

	
	
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
	 *         &lt;element ref=&quot;{}key&quot;/&gt;
	 *       &lt;/choice&gt;
	 *       &lt;attribute ref=&quot;{}base-url&quot;/&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "key" })
	public static class Float {

		protected List<Key> key;
		@XmlAttribute(name = "base-url")
		protected String baseUrl;

		/**
		 * Gets the value of the key property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the key property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getKey().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Key }
		 * 
		 * 
		 */
		public List<Key> getKey() {
			if (key == null) {
				key = new ArrayList<Key>();
			}
			return this.key;
		}

		/**
		 * Gets the value of the baseUrl property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getBaseUrl() {
			return baseUrl;
		}

		/**
		 * Sets the value of the baseUrl property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setBaseUrl(String value) {
			this.baseUrl = value;
		}

	}
	
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
	 *         &lt;element ref=&quot;{}key&quot; maxOccurs=&quot;unbounded&quot;/&gt;
	 *       &lt;/choice&gt;
	 *       &lt;attribute ref=&quot;{}base-url&quot;/&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "key" })
	public static class MainFrame {

		protected List<Key> key;
		@XmlAttribute(name = "base-url")
		protected String baseUrl;

		/**
		 * Gets the value of the key property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the key property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getKey().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Key }
		 * 
		 * 
		 */
		public List<Key> getKey() {
			if (key == null) {
				key = new ArrayList<Key>();
			}
			return this.key;
		}

		/**
		 * Gets the value of the baseUrl property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getBaseUrl() {
			return baseUrl;
		}

		/**
		 * Sets the value of the baseUrl property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setBaseUrl(String value) {
			this.baseUrl = value;
		}

	}
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
	 *         &lt;element ref=&quot;{}key&quot; maxOccurs=&quot;unbounded&quot;/&gt;
	 *       &lt;/choice&gt;
	 *       &lt;attribute ref=&quot;{}base-url&quot;/&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "key" })
	public static class MultiLineInput {

		protected List<Key> key;
		@XmlAttribute(name = "base-url")
		protected String baseUrl;

		/**
		 * Gets the value of the key property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the key property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getKey().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Key }
		 * 
		 * 
		 */
		public List<Key> getKey() {
			if (key == null) {
				key = new ArrayList<Key>();
			}
			return this.key;
		}

		/**
		 * Gets the value of the baseUrl property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getBaseUrl() {
			return baseUrl;
		}

		/**
		 * Sets the value of the baseUrl property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setBaseUrl(String value) {
			this.baseUrl = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
	 *         &lt;element ref=&quot;{}key&quot; maxOccurs=&quot;unbounded&quot;/&gt;
	 *       &lt;/choice&gt;
	 *       &lt;attribute ref=&quot;{}base-url&quot;/&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "key" })
	public static class Select {

		protected List<Key> key;
		@XmlAttribute(name = "base-url")
		protected String baseUrl;

		/**
		 * Gets the value of the key property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the key property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getKey().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Key }
		 * 
		 * 
		 */
		public List<Key> getKey() {
			if (key == null) {
				key = new ArrayList<Key>();
			}
			return this.key;
		}

		/**
		 * Gets the value of the baseUrl property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getBaseUrl() {
			return baseUrl;
		}

		/**
		 * Sets the value of the baseUrl property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setBaseUrl(String value) {
			this.baseUrl = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
	 *         &lt;element ref=&quot;{}key&quot; maxOccurs=&quot;unbounded&quot;/&gt;
	 *       &lt;/choice&gt;
	 *       &lt;attribute ref=&quot;{}base-url&quot;/&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "key" })
	public static class SingleLineInput {

		protected List<Key> key;
		@XmlAttribute(name = "base-url")
		protected String baseUrl;

		/**
		 * Gets the value of the key property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the key property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getKey().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Key }
		 * 
		 * 
		 */
		public List<Key> getKey() {
			if (key == null) {
				key = new ArrayList<Key>();
			}
			return this.key;
		}

		/**
		 * Gets the value of the baseUrl property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getBaseUrl() {
			return baseUrl;
		}

		/**
		 * Sets the value of the baseUrl property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setBaseUrl(String value) {
			this.baseUrl = value;
		}

	}

}
