/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *///
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 02:11:32 下午 CST 
//


package com.wisii.edit.tag.schema.wdems;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.wisii.com/wdems}tableInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}data" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}include" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="bond">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="sq"/>
 *             &lt;enumeration value="eq"/>
 *             &lt;enumeration value="vert"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="translateUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="swingdatasource" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valueNumber" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="root" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="struts" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="table1"/>
 *             &lt;enumeration value="table2"/>
 *             &lt;enumeration value="tree"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tableInfoOrDataOrInclude"
})
@XmlRootElement(name = "dataSource")
public class DataSource {

    @XmlElements({
        @XmlElement(name = "data", type = Data.class),
        @XmlElement(name = "include", type = Include.class),
        @XmlElement(name = "tableInfo", type = TableInfo.class)
    })
    protected List<Object> tableInfoOrDataOrInclude;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute
    protected String bond;
    @XmlAttribute
    protected String translateUrl;
    @XmlAttribute
    protected String swingdatasource;
    @XmlAttribute
    protected String valueNumber;
    @XmlAttribute
    protected String root;
    @XmlAttribute(required = true)
    protected String struts;

    /**
     * Gets the value of the tableInfoOrDataOrInclude property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tableInfoOrDataOrInclude property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTableInfoOrDataOrInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data }
     * {@link Include }
     * {@link TableInfo }
     * 
     * 
     */
    public List<Object> getTableInfoOrDataOrInclude() {
        if (tableInfoOrDataOrInclude == null) {
            tableInfoOrDataOrInclude = new ArrayList<Object>();
        }
        return this.tableInfoOrDataOrInclude;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBond() {
        return bond;
    }

    /**
     * Sets the value of the bond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBond(String value) {
        this.bond = value;
    }

    /**
     * Gets the value of the translateUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranslateUrl() {
        return translateUrl;
    }

    /**
     * Sets the value of the translateUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranslateUrl(String value) {
        this.translateUrl = value;
    }

    /**
     * Gets the value of the swingdatasource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwingdatasource() {
        return swingdatasource;
    }

    /**
     * Sets the value of the swingdatasource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwingdatasource(String value) {
        this.swingdatasource = value;
    }

    /**
     * Gets the value of the valueNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueNumber() {
        if (valueNumber == null) {
            return "1";
        } else {
            return valueNumber;
        }
    }

    /**
     * Sets the value of the valueNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueNumber(String value) {
        this.valueNumber = value;
    }

    /**
     * Gets the value of the root property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoot() {
        return root;
    }

    /**
     * Sets the value of the root property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoot(String value) {
        this.root = value;
    }

    /**
     * Gets the value of the struts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStruts() {
        return struts;
    }

    /**
     * Sets the value of the struts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStruts(String value) {
        this.struts = value;
    }

}
