/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *///
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 02:11:32 下午 CST 
//


package com.wisii.edit.tag.schema.wdems;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.wisii.com/wdems}button" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}a" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}input" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}date" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}select" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}group" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}table" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="select" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "buttonOrAOrInput"
})
@XmlRootElement(name = "form")
public class Form {

    @XmlElements({
        @XmlElement(name = "a", type = A.class),
        @XmlElement(name = "button", type = Button.class),
        @XmlElement(name = "select", type = Select.class),
        @XmlElement(name = "group", type = Group.class),
        @XmlElement(name = "table", type = Table.class),
        @XmlElement(name = "input", type = Input.class),
        @XmlElement(name = "date", type = Date.class)
    })
    protected List<Object> buttonOrAOrInput;
    @XmlAttribute
    protected String select;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected String title;

    /**
     * Gets the value of the buttonOrAOrInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buttonOrAOrInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getButtonOrAOrInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link A }
     * {@link Button }
     * {@link Select }
     * {@link Group }
     * {@link Table }
     * {@link Input }
     * {@link Date }
     * 
     * 
     */
    public List<Object> getButtonOrAOrInput() {
        if (buttonOrAOrInput == null) {
            buttonOrAOrInput = new ArrayList<Object>();
        }
        return this.buttonOrAOrInput;
    }

    /**
     * Gets the value of the select property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelect() {
        return select;
    }

    /**
     * Sets the value of the select property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelect(String value) {
        this.select = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

}
