/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *///
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 02:11:32 下午 CST 
//


package com.wisii.edit.tag.schema.wdems;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.wisii.com/wdems}valAttrGroup"/>
 *       &lt;attGroup ref="{http://www.wisii.com/wdems}uiCommon"/>
 *       &lt;attGroup ref="{http://www.wisii.com/wdems}commonAttr"/>
 *       &lt;attribute name="isSearchable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="type" default="combobox">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="list"/>
 *             &lt;enumeration value="combobox"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="sortColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="searchQueue" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="showList">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="check"/>
 *             &lt;enumeration value="uncheck"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="src" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="next" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="view" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="isEdit" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="lines" default="20">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="5"/>
 *             &lt;maxInclusive value="200"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="sort" default="c">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="p"/>
 *             &lt;enumeration value="n"/>
 *             &lt;enumeration value="c"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="multiple" default="1">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "select")
public class Select {

    @XmlAttribute
    protected Boolean isSearchable;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    protected String sortColumn;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String searchQueue;
    @XmlAttribute
    protected String showList;
    @XmlAttribute(required = true)
    protected String src;
    @XmlAttribute
    protected String next;
    @XmlAttribute
    protected String view;
    @XmlAttribute
    protected Boolean isEdit;
    @XmlAttribute
    protected Integer lines;
    @XmlAttribute
    protected String sort;
    @XmlAttribute
    protected Integer multiple;
    @XmlAttribute
    protected String onBlur;
    @XmlAttribute
    protected String onSelected;
    @XmlAttribute
    protected String onKeyPress;
    @XmlAttribute
    protected String onKeyDown;
    @XmlAttribute
    protected String onKeyUp;
    @XmlAttribute
    protected String onEdit;
    @XmlAttribute
    protected String onClick;
    @XmlAttribute
    protected String onResult;
    @XmlAttribute
    protected String appearance;
    @XmlAttribute
    protected String width;
    @XmlAttribute
    protected String height;
    @XmlAttribute
    protected String hint;
    @XmlAttribute
    protected String hintType;
    @XmlAttribute
    protected Boolean isReload;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected String conn;

    /**
     * Gets the value of the isSearchable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsSearchable() {
        if (isSearchable == null) {
            return false;
        } else {
            return isSearchable;
        }
    }

    /**
     * Sets the value of the isSearchable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSearchable(Boolean value) {
        this.isSearchable = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "combobox";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the sortColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortColumn() {
        return sortColumn;
    }

    /**
     * Sets the value of the sortColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortColumn(String value) {
        this.sortColumn = value;
    }

    /**
     * Gets the value of the searchQueue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchQueue() {
        return searchQueue;
    }

    /**
     * Sets the value of the searchQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchQueue(String value) {
        this.searchQueue = value;
    }

    /**
     * Gets the value of the showList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowList() {
        return showList;
    }

    /**
     * Sets the value of the showList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowList(String value) {
        this.showList = value;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrc(String value) {
        this.src = value;
    }

    /**
     * Gets the value of the next property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNext() {
        return next;
    }

    /**
     * Sets the value of the next property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNext(String value) {
        this.next = value;
    }

    /**
     * Gets the value of the view property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getView() {
        if (view == null) {
            return "1";
        } else {
            return view;
        }
    }

    /**
     * Sets the value of the view property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setView(String value) {
        this.view = value;
    }

    /**
     * Gets the value of the isEdit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsEdit() {
        if (isEdit == null) {
            return false;
        } else {
            return isEdit;
        }
    }

    /**
     * Sets the value of the isEdit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEdit(Boolean value) {
        this.isEdit = value;
    }

    /**
     * Gets the value of the lines property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLines() {
        if (lines == null) {
            return  20;
        } else {
            return lines;
        }
    }

    /**
     * Sets the value of the lines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLines(Integer value) {
        this.lines = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSort() {
        if (sort == null) {
            return "c";
        } else {
            return sort;
        }
    }

    /**
     * Sets the value of the sort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSort(String value) {
        this.sort = value;
    }

    /**
     * Gets the value of the multiple property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMultiple() {
        if (multiple == null) {
            return  1;
        } else {
            return multiple;
        }
    }

    /**
     * Sets the value of the multiple property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMultiple(Integer value) {
        this.multiple = value;
    }

    /**
     * Gets the value of the onBlur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnBlur() {
        return onBlur;
    }

    /**
     * Sets the value of the onBlur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnBlur(String value) {
        this.onBlur = value;
    }

    /**
     * Gets the value of the onSelected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnSelected() {
        return onSelected;
    }

    /**
     * Sets the value of the onSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnSelected(String value) {
        this.onSelected = value;
    }

    /**
     * Gets the value of the onKeyPress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnKeyPress() {
        return onKeyPress;
    }

    /**
     * Sets the value of the onKeyPress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnKeyPress(String value) {
        this.onKeyPress = value;
    }

    /**
     * Gets the value of the onKeyDown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnKeyDown() {
        return onKeyDown;
    }

    /**
     * Sets the value of the onKeyDown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnKeyDown(String value) {
        this.onKeyDown = value;
    }

    /**
     * Gets the value of the onKeyUp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnKeyUp() {
        return onKeyUp;
    }

    /**
     * Sets the value of the onKeyUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnKeyUp(String value) {
        this.onKeyUp = value;
    }

    /**
     * Gets the value of the onEdit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnEdit() {
        return onEdit;
    }

    /**
     * Sets the value of the onEdit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnEdit(String value) {
        this.onEdit = value;
    }

    /**
     * Gets the value of the onClick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnClick() {
        return onClick;
    }

    /**
     * Sets the value of the onClick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnClick(String value) {
        this.onClick = value;
    }

    /**
     * Gets the value of the onResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnResult() {
        return onResult;
    }

    /**
     * Sets the value of the onResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnResult(String value) {
        this.onResult = value;
    }

    /**
     * Gets the value of the appearance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppearance() {
        return appearance;
    }

    /**
     * Sets the value of the appearance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppearance(String value) {
        this.appearance = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the hint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHint() {
        return hint;
    }

    /**
     * Sets the value of the hint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHint(String value) {
        this.hint = value;
    }

    /**
     * Gets the value of the hintType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHintType() {
        return hintType;
    }

    /**
     * Sets the value of the hintType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHintType(String value) {
        this.hintType = value;
    }

    /**
     * Gets the value of the isReload property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsReload() {
        if (isReload == null) {
            return false;
        } else {
            return isReload;
        }
    }

    /**
     * Sets the value of the isReload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsReload(Boolean value) {
        this.isReload = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the conn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConn() {
        return conn;
    }

    /**
     * Sets the value of the conn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConn(String value) {
        this.conn = value;
    }

}
