/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *///
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 02:11:32 下午 CST 
//


package com.wisii.edit.tag.schema.wdems;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.wisii.com/wdems}input" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}select" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}date" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}checkbox" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}group" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}button" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}form" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}table" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}connwith" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}validation" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}dataSource" minOccurs="0"/>
 *         &lt;element ref="{http://www.wisii.com/wdems}swingdatasource" minOccurs="0"/>
 *         &lt;element name="xpath" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dpath" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputOrSelectOrDate"
})
@XmlRootElement(name = "wdems")
public class Wdems {

    @XmlElements({
        @XmlElement(name = "validation", type = Validation.class),
        @XmlElement(name = "button", type = Button.class),
        @XmlElement(name = "select", type = Select.class),
        @XmlElement(name = "xpath", type = Wdems.Xpath.class),
        @XmlElement(name = "dataSource", type = DataSource.class),
        @XmlElement(name = "swingdatasource", type = Swingdatasource.class),
        @XmlElement(name = "group", type = Group.class),
        @XmlElement(name = "connwith", type = Connwith.class),
        @XmlElement(name = "date", type = Date.class),
        @XmlElement(name = "checkbox", type = Checkbox.class),
        @XmlElement(name = "form", type = Form.class),
        @XmlElement(name = "table", type = Table.class),
        @XmlElement(name = "input", type = Input.class),
        @XmlElement(name = "popupbrowser", type = PopupBrowser.class),
        @XmlElement(name = "graphic", type = Graphic.class),
    })
    protected List<Object> inputOrSelectOrDate;

    /**
     * Gets the value of the inputOrSelectOrDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputOrSelectOrDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputOrSelectOrDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Validation }
     * {@link Button }
     * {@link Select }
     * {@link Wdems.Xpath }
     * {@link DataSource }
     * {@link Swingdatasource }
     * {@link Group }
     * {@link Connwith }
     * {@link Date }
     * {@link Checkbox }
     * {@link Form }
     * {@link Table }
     * {@link Input }
     * 
     * 
     */
    public List<Object> getInputOrSelectOrDate() {
        if (inputOrSelectOrDate == null) {
            inputOrSelectOrDate = new ArrayList<Object>();
        }
        return this.inputOrSelectOrDate;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dpath" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dpath"
    })
    public static class Xpath {

        @XmlElement(required = true)
        protected Object dpath;

        /**
         * Gets the value of the dpath property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDpath() {
            return dpath;
        }

        /**
         * Sets the value of the dpath property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDpath(Object value) {
            this.dpath = value;
        }

    }

}
